version: "3"
services:
  myspringapp:
    image: myspringappv3
    container_name: myspringappv3
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - F:/data/db:/data/db